version: "3"
services:
  mysql:
    image: marmotjs/marmot-mysql
    restart: always
    volumes:
      - $HOME/marmot_home/mysql_data:/var/lib/mysql
  web:
    image: marmotjs/marmot-web
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:9900"
    environment:
      - MYSQL_HOST=mysql
      - MARMOT_HOST=127.0.0.1 # replace it with your hostname: MARMOT_HOST=example.com
  nginx:
    image: marmotjs/marmot-nginx
    restart: always
    volumes:
      - $HOME/marmot_home/static:/usr/share/nginx/html:ro
    ports:
      - "9920:80"
  datahub:
    image: macacajs/macaca-datahub
    restart: always
    volumes:
      - $HOME/marmot_home/macaca-datahub:/root/.macaca-datahub
    ports:
      - "9930:9200"
      - "9300:9300"
